name: Publish

on:
  release:
    types: [ published ]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          registry-url: 'https://registry.npmjs.org/'
      - run: pnpm install

      - name: Build lib
        run: pnpm --filter "vuecomotive-scroll" lib:build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: pnpm publish lib --no-git-checks
