name: Publish

on:
  workflow_run:
    workflows: [ Release ]
    types: [ completed ]

  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      dist_file: ${{ steps.pack.outputs.tar }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install

      - name: Build lib
        run: pnpm lib:build

      - name: Create package distribution
        id: pack
        working-directory: lib
        run: |
          pnpm pack
          echo "tar=$(find -name '*.tgz')" >> $GITHUB_OUTPUT
          cp *.tgz ..

      - uses: actions/upload-artifact@v3
        with:
          name: package-dist
          path: ${{ steps.pack.outputs.tar }}
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: npm
      url: https://www.npmjs.com/package/potiah
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package-dist

      - name: Publish package distribution to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          package: ${{ needs.build.outputs.dist_file }}
