name: Release

on:
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # it would be nice to be able to generate changelogs there

      - name: Create & publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
